### ISSUE TITLE
connector: establish direct connection between cron and buildkite trigger

### ISSUE THREAD

**Issue by scriptnull** [scriptnull/waymond#7]
We may need to do a whole bunch of refactoring to make this work.

```toml
[[trigger]]
type = "cron"
id = "global_cron"
expression = "*/1 * * * *"

[[trigger]]
type = "buildkite"
id = "my_buildkite_org"
# set BUILDKITE_TOKEN environment variable

[[connect]]
type = "direct"
id = "check_my_buildkite_org_queues_periodically"
from = "trigger.global_cron"
to = "trigger.my_buildkite_org"
```
